services:
  server:
    container_name: tcp_server
    image: tcp-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: always
    network_mode: host
  client-1:
    container_name: tcp_client_1
    image: tcp-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    network_mode: host
    environment:
      QUANTITY: "1"
      NUMBER: "1"
    depends_on:
      - server
  client-2:
    container_name: tcp_client_2
    image: tcp-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    network_mode: host
    environment:
      QUANTITY: "100"
      NUMBER: "3"
    depends_on:
      - server