services:
  server:
    image: tcp-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: always
    networks:
      - tcp_network
  client:
    image: tcp-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    restart: always
    networks:
      - tcp_network
networks:
  tcp_network:
    driver: bridge